#!/bin/bash
# Created by the University of Melbourne job script generator for SLURM
# Tue Apr 02 2019 10:31:59 GMT+1100 (Australian Eastern Daylight Time)

# Partition for the job:
#SBATCH --partition=cloud,physical

# Multithreaded (SMP) job: must run on one node and the cloud partition
#SBATCH --nodes=1

# array
#SBATCH --array=1-8

# The name of the job:
#SBATCH --job-name="Shovill"

# The project ID which this job should run under:
#SBATCH --account="punim0599"

# Maximum number of tasks/CPU cores used by the job:
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8

# Use this email address:
#SBATCH --mail-user=jmmans@student.unimelb.edu.au

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-0:10:00

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

# delay - a decent delay
wt=$((${SLURM_ARRAY_TASK_ID} * 15))
sleep $wt

# setting files name
cd /data/cephfs/punim0599/Jesse/emm75/M75/fasta/
ls | while read line; do
	if [[ "$line" == *".fa.fa"* ]] ; then
		 var1=${line:0:-3}
fi

# variables used 
out="/data/cephfs/punim0599/Jesse/emm75/M75/fasta/${var1}"
mv ./${line} ${out}

done

