#!/bin/bash
# Created by the University of Melbourne job script generator for SLURM
# Tue Apr 02 2019 10:31:59 GMT+1100 (Australian Eastern Daylight Time)

# Partition for the job:
#SBATCH --partition=cloud,physical

# Multithreaded (SMP) job: must run on one node and the cloud partition
#SBATCH --nodes=1

# The name of the job:
#SBATCH --job-name="GWAS"

# The project ID which this job should run under:
#SBATCH --account="punim0599"

# Maximum number of tasks/CPU cores used by the job:
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4

# Use this email address:
#SBATCH --mail-user=jmmans@student.unimelb.edu.au

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-3:00:00

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

# needed modules
module load PopPUNK/1.1.3-intel-2017.u2-Python-3.6.4
module load Python/3.5.2-GCC-6.2.0
module load DendroPy/4.1.0-intel-2016.u3-Python-3.5.2
module load hdbscan/0.8.18-intel-2017.u2-Python-3.6.4
module load matplotlib/1.5.1-intel-2016.u3-Python-2.7.9
module load networkx/2.2-intel-2017.u2-Python-3.6.4
module load numba/0.36.2-intel-2017.u2-Python-3.6.4
module load pandas/0.18.1-intel-2016.u3-Python-3.5.2
module load scikit-learn/0.18-intel-2016.u3-Python-2.7.9
module load sharedmem/0.3.5-intel-2017.u2-Python-3.6.4

# variables used 
out="/data/cephfs/punim0599/Jesse/emm75/GWAS/pyseer.assoc"

# pyseer
[[ -d "$out" ]] ||  pyseer --phenotypes pres_abs.csv --kmers kmers.gz --distances mashoutput.tsv --min-af 0.01 --max-af 0.99 --cpu 4 --filter-pvalue 1E-8 > $out

done
