#!/bin/bash

# Created by the University of Melbourne job script generator for SLURM
# Tue Apr 02 2019 10:31:59 GMT+1100 (Australian Eastern Daylight Time)

# Partition for the job:
#SBATCH --partition=cloud,physical

# Multithreaded (SMP) job: must run on one node and the cloud partition
#SBATCH --nodes=1

# array
#SBATCH --array=1-8

# The name of the job:
#SBATCH --job-name="Snippy_code"

# The project ID which this job should run under:
#SBATCH --account="punim0599"

# Maximum number of tasks/CPU cores used by the job:
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8

# Use this email address:
#SBATCH --mail-user=jmmans@student.unimelb.edu.au

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-4:00:00

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

# delay - a decent delay
wt=$((${SLURM_ARRAY_TASK_ID} * 15))
sleep $wt

#modules
module load Prokka/1.13-intel-2016.u3-BioPerl-1.6.924
module load Java/9.0.4
module load BLAST+/2.7.1-spartan_intel-2017.u2

# like a for loop but better 
cd /data/cephfs/punim0599/Jesse/emm75/M75_jesse/fa
ls | while read line; do
line=${line:0:-3}

#variable shortening
out='/data/cephfs/punim0599/Jesse/emm75/M75_jesse/prokka'

#prokka called the line
prokka --prefix ${line} --outdir $out/${line} /data/cephfs/punim0599/Jesse/emm75/M75_jesse/fa/${line}

done
